name: Cargo Build & Test

on:
  pull_request:

jobs:
  build_and_test:
    name: pdb-rs
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        toolchain:
          - 1.82
          - stable
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: cargo test --locked
      - run: cargo test --locked --release
      - run: cargo build --locked --release
      - run: rustup component add clippy
      - run: cargo clippy --locked
      - run: rustup component add rustfmt
      - run: cargo fmt --check
